# CMake initial cache file for Derecho using Intel compiler

SET(CRAYPE_LINK_TYPE "dynamic" CACHE STRING "") 

SET(NETCDF_DIR $ENV{NETCDF} CACHE FILEPATH "")
SET(PNETCDF_DIR $ENV{PNETCDF} CACHE FILEPATH "")
SET(HDF5_DIR $ENV{NCAR_ROOT_HDF5} CACHE FILEPATH "")

#for scorpio
SET(NetCDF_C_PATH $ENV{NETCDF} CACHE FILEPATH "")
SET(NetCDF_Fortran_PATH $ENV{NETCDF} CACHE FILEPATH "")

SET(BUILD_HOMME_WITHOUT_PIOLIBRARY TRUE CACHE BOOL "")

SET(HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

SET(WITH_PNETCDF FALSE CACHE FILEPATH "")

SET(ADD_LINKER_FLAGS "-L/$ENV{NETCDF}/lib -lnetcdff -lnetcdf" CACHE STRING "")
SET(ADD_Fortran_FLAGS "-traceback" CACHE STRING "")

SET(USE_QUEUING FALSE CACHE BOOL "")

SET(BUILD_HOMME_THETA_KOKKOS TRUE CACHE BOOL "")

SET(USE_TRILINOS OFF CACHE BOOL "")

SET(Kokkos_ENABLE_OPENMP OFF CACHE BOOL "")
SET(Kokkos_ENABLE_CUDA OFF CACHE BOOL "")
SET(Kokkos_ENABLE_CUDA_LAMBDA OFF CACHE BOOL "")
SET(Kokkos_ARCH_VOLTA70 OFF CACHE BOOL "")
SET(Kokkos_ARCH_AMPERE80 OFF CACHE BOOL "")
SET(Kokkos_ARCH_ZEN3 ON CACHE BOOL "")
SET(Kokkos_ENABLE_EXPLICIT_INSTANTIATION OFF CACHE BOOL "")
#SET(Kokkos_ENABLE_CUDA_ARCH_LINKING OFF CACHE BOOL "")

SET(CMAKE_C_COMPILER "cc" CACHE STRING "")
SET(CMAKE_Fortran_COMPILER "ftn" CACHE STRING "")
SET(CMAKE_CXX_COMPILER "CC" CACHE STRING "")

SET(CXXLIB_SUPPORTED_CACHE FALSE CACHE BOOL "")

SET(ENABLE_OPENMP OFF CACHE BOOL "")
SET(ENABLE_COLUMN_OPENMP OFF CACHE BOOL "")
SET(ENABLE_HORIZ_OPENMP OFF CACHE BOOL "")

SET(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "")

SET(USE_NUM_PROCS 128 CACHE STRING "")

SET(USE_MPIEXEC "mpiexec" CACHE STRING "")
SET(CPRNC_DIR /glade/campaign/cesm/cesmdata/cprnc CACHE FILEPATH "")
SET(HOMME_USE_MKL "TRUE" CACHE FILEPATH "") # for Intel
SET(USE_QUEUING FALSE CACHE BOOL "")